apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod5
  name: pod5
spec:
  containers:
  - image: busybox:1.31.0
    name: pod5-container
    command:
      - "/bin/sh"
      - "-c"
      - "touch /tmp/ready && sleep 1d"
    resources: {}
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/ready
      initialDelaySeconds: 5
      periodSeconds: 10
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
