apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: project-q6-api
    project: q6-api
  name: project-q6-api
spec:
  containers:
  - image: nginx:1.17.3-alpine
    name: project-q6-api
    ports:
      - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
